### ISSUE TITLE
minimap position

### ISSUE THREAD

**Issue by sybenx** [DeDiamondPro/SkyGuide#18]
Allow setting the location of the minimap to a different corner of the screen via ingame config.

**Comment by DeDiamondPro** [comment]
> Allow setting the location of the minimap to a different corner of the screen via ingame config.

This is already possible, open the settings menu with `/skyguide`, go to the `Mini-Map` category and there will be a dropdown called `Mini-Map Location` where you can chose the corner.

If you're using the oneconfig beta you can move the mini-map in oneconfig's hud editor, which you can open by doing `/skyguide` and then pressing the `edit hud` button in the bottom left
