### ISSUE TITLE
Adds a dark font backround when minimap is on

### ISSUE THREAD

**Issue by Cuteistfox** [DeDiamondPro/SkyGuide#24]
Minimap off
![Screenshot_20240530_064219](https://github.com/DeDiamondPro/SkyGuide/assets/108002756/0b69702b-0f0d-4744-bd88-b055d85ee42b)
Minimap on
![Screenshot_20240530_064243](https://github.com/DeDiamondPro/SkyGuide/assets/108002756/812b94e8-653c-41a9-b200-bd9b8e2f113c)
 (look at the botton left corner cause i couldent manage to crop it)

### Mods
` 3dSkinLayers-forge-mc1.8.9-1.2.0.jar  DamageTint-1.8.9-forge-3.3.0.jar  Keystrokes-1.8.9-forge-1.0.0.jar           PolyNametag-1.8.9-forge-1.0.2.jar antighost-1.8.9-forge11.15.1.1722-1.1.jar   EvergreenHUD-1.8.9-forge-2.1.5.jar         'LevelHead-8.2.2 (1.8.9).jar' PolySprint-1.8.9-forge-1.0.0.jar 'Scrollable Tooltips-1.4 (1.8.9).jar'
 ArrowPath-v1.0.jar  FancyWarpMenu-2.0-beta.1+121.jar            Mixmetica-1.8.9-forge-2.0.4.jar           'Popup Events-1.3.2 (1.8.9).jar'           SkyblockAddons-1.9.0-beta.9+303-for-MC-1.8.9.jar
'AutoGG-4.1.3 (1.8.9).jar'  NotEnoughUpdates-2.2.2.jar                 Potion_Effects_1.8.9-forge_1.0.jar       'SkyGuide (1.8.9-forge)-1.3.0+oneconfig.jar'
 autoskyblockrejoin-1.8.9-forge-1.3.3.jar    great-scrollable-tooltips-1.2.0.jar         Optibye-1.0.0-dep.jar                      preview_OptiFine_1.8.9_HD_U_M6_pre2.jar   SkyHanni-0.26.Beta.3.jar
'Autotip-3.1.1 (1.8.9_forge).jar'           'Hypixel Autocomplete-1.1 (1.8.9).jar'       OverflowAnimations-1.8.9-forge-2.1.1.jar   QuickQuit-1.0.1.jar                       smooth-scrolling-everywhere-1.2.jar
 BazaarNotifier-1.7.2.jar                   'Hytils Reborn-1.8.9-forge-1.6.1.jar'        ParticlesEnhanced-1.3.2.jar                realmsfixlegacyforge-1.0.0.jar           'TNT Time-1.1 (1.8.9).jar'
 BehindYouV3-1.8.9-forge-3.1.2.jar           Hytools-1.6.jar                            'Patcher-1.8.9 (1.8.9).jar'                 REDACTION-1.8.9-forge-1.3.7.jar           veloxcaelo-1.0.2.jar
 Chatting-1.8.9-forge-1.5.3.jar              IdleTweaks-1.0.5.jar                        phosphor-universal.jar                     ReportPlus-1.0.0.jar                      waveycapes-forge-mc1.8.9-1.2.0.jar
 CrashPatch-1.8.9-forge-2.0.0.jar            Insomnia-1.0-REL.jar                        Polished-GUI-1.0.0.jar                    'Resourcify (1.8.9-forge)-1.3.6.jar'
`
(i just copyed the ls output)

**Comment by DeDiamondPro** [comment]
An update has been pushed to OneConfig that fixes this issue.
